<a href="https://colab.research.google.com/github/mathuraryan036-collab/ML-GOOGLE-COLAB-/blob/main/4_7_Handling_Imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Imbalanced Dataset - A dataset with an unequal class distribution

In [ ]:
# importing the dependencies
import numpy as np
import pandas as pd

In [ ]:
# loading the dataset to the pandas Dataframe
credit_card_data = pd.read_csv('/content/credit_data.csv')

In [ ]:
# first 5 rows of the dataframe
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
190234,128749.0,2.041966,0.174409,-1.711336,0.533765,0.156949,-1.447242,0.244206,-0.354569,0.633990,...,0.200018,0.739193,-0.012997,-0.084867,0.227029,-0.097686,-0.001726,-0.031748,6.68,0.0
190235,128749.0,-0.217502,0.913453,0.020849,-0.835175,0.541120,-0.592428,0.887042,-0.004344,-0.013578,...,-0.272937,-0.593312,0.026502,-0.429509,-0.432099,0.151735,0.354753,0.137631,13.99,0.0
190236,128750.0,2.068935,0.013847,-2.275414,0.305170,0.938897,0.151034,-0.079624,0.024150,0.625386,...,-0.057606,0.074640,-0.084997,-0.479828,0.230444,0.654925,-0.051699,-0.043789,10.00,0.0
190237,128750.0,1.991961,-2.015101,-0.926487,-1.540712,-1.580846,-0.305510,-1.254461,-0.005932,-1.073746,...,-0.052382,-0.037013,0.079387,-0.541760,-0.347793,-0.176883,-0.013358,-0.037445,158.00,0.0
190238,128750.0,1.810118,-0.766400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# distribution of the Two classes
credit_card_data['Class'].value_counts()

Class
0.0    189867
1.0       371
Name: count, dtype: int64

This is highly imbalanced dataset

0 --> Legit Transactions

1 --> Fraud Transactions

In [ ]:
# separating the legit and fraud transactions
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(189867, 31)
(371, 31)

Undersampling

Build a sample dataset containing similar distribution of Legit and Fraud Transactions

Number of Fraud Transactions --> 371

In [ ]:
legit_sample = legit.sample(n=371)

In [ ]:
print(legit_sample.shape)

(371, 31)

Concatenate the Two Dataframes

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
26267,33976.0,0.413666,-0.997355,0.119929,1.779250,-0.696859,-0.243079,0.565349,-0.126600,0.248376,...,0.146220,-0.206992,-0.352377,0.423260,0.475578,-0.372082,-0.031820,0.084478,385.12,0.0
37219,38861.0,-3.157215,2.660765,-0.859280,-1.600706,-1.555109,-0.632797,-1.388134,2.375270,-0.188633,...,-0.002189,-0.427364,0.140968,-0.503902,0.038876,0.785973,0.044489,0.079557,1.90,0.0
45847,42524.0,-0.364981,0.436863,2.365450,0.494083,-0.283730,0.549557,0.209401,0.221263,-0.078380,...,0.215185,0.678286,-0.066742,-0.018750,-0.241014,-0.415726,-0.082686,-0.189743,45.00,0.0
53149,45836.0,-0.682475,1.231246,1.365138,0.280625,0.125009,-0.729014,0.917648,-0.638602,-0.254675,...,0.217066,0.676484,-0.150098,0.464110,-0.463506,0.326214,-0.717768,-0.055377,5.99,0.0
118589,75139.0,-0.513769,0.654928,1.901009,-0.100082,-0.035341,-1.157064,1.084143,-0.484869,-0.508121,...,-0.016277,0.203751,-0.277243,1.035783,0.307407,1.191190,-0.208324,-0.165789,28.00,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
183106,125658.0,0.224414,2.994499,-3.432458,3.986519,3.760233,0.165640,1.099378,-0.654557,-2.435416,...,0.491337,-0.984223,-0.421979,-1.048058,0.726412,0.268625,0.283689,0.419102,0.00,1.0
184379,126219.0,-1.141559,1.927650,-3.905356,-0.073943,-0.044858,-1.756999,-1.217416,0.364563,-2.770148,...,0.102081,-0.531496,-0.328741,0.393100,0.568435,0.786605,-0.146102,0.076211,25.00,1.0
189587,128471.0,0.909124,1.337658,-4.484728,3.245358,-0.417809,-0.762119,-2.506349,0.694164,-0.467556,...,0.586829,0.594078,-0.252120,0.325439,0.562766,-0.256278,0.652674,0.319879,67.90,1.0
189701,128519.0,-4.599447,2.762540,-4.656530,5.201403,-2.470388,-0.357618,-3.767189,0.061466,-1.836200,...,1.581480,0.261333,0.621415,0.994110,-0.687853,-0.337531,-1.612791,1.231425,93.35,1.0
189878,128595.0,-5.313774,2.664274,-4.250707,0.394707,-0.391383,0.683526,-5.133671,-7.907790,0.215475,...,8.664662,-2.716383,0.483559,0.079235,0.311065,0.555544,0.176740,0.362907,1.00,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    371
1.0    371
Name: count, dtype: int64